### ISSUE TITLE
similar to `get-value`

### ISSUE THREAD

**Issue by tunnckoCore** [bevacqua/breadcrumb#1]
Heya there, Nico! :)

get review this [jonschlinkert/get-value](https://github.com/jonschlinkert/get-value), his benchmarks and related projects like `set-value`, `get-property` and etc :)

Jon made one of the fastest [implementations](https://github.com/jonschlinkert/get-value/tree/master/benchmark/code).

**Comment by tunnckoCore** [comment]
And boy, that description rocks, lol.

**Comment by bevacqua** [comment]
Didn't know that project, just threw one together cause I needed it
